#name: Build
#on:
#  push:
#    branches:
#      - master
#  pull_request:
#    types: [opened, synchronize, reopened]
    
# Common maven build workflow for java applications
# Use https://github.com/actions/checkout in order to checkout project
name: Java CI Maven

on:
  workflow_call:
    inputs:
      sonarqube_url:
        required: true
        type: string
      sonarqube_organization:
        required: true
        type: string
      sonarqube_project_key:
        required: true
        type: string
    secrets:
      sonarqube_token:
        required: true
        
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ inputs.sonarqube_token }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.host.url=${{ inputs.sonarqube_url }} -Dsonar.organization=${{ inputs.sonarqube_organization }} -Dsonar.projectKey=${{ inputs.sonarqube_project_key}}
