# Common maven build workflow for java applications
# Use https://github.com/actions/checkout in order to checkout project
name: Java CI Maven

on:
  workflow_call:
    inputs:
      sonarqube_url:
        required: true
        type: string
      sonarqube_organization:
        required: true
        type: string
    secrets:
      github_token:
        required: true
      sonarqube_token:
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean install --file pom.xml
      
    - name: sonarqube
      run:  mvn sonar:sonar -Dsonar.organization=${{ inputs.sonarqube_organization }} -Dsonar.host.url=${{ inputs.sonarqube_url }} -Dsonar.login=${{ secrets.sonarqube_token }}
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
