# Common maven build workflow for java applications
name: Java CI Maven

on:
  workflow_call:
    inputs:
      sonar_url:
        required: true
        type: string
      sonar_username:
        required: true
        type: string
      sonar_organization:
        required: true
        type: string
    secrets:
      github_token:
        required: true
      sonar_token:
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean install --file pom.xml
      
    - name: sonarqube
      run:  mvn sonar:sonar -Dsonar.organization=${{ secrets.sonar_organization }} -Dsonar.host.url=${{ secrets.sonar_url }} -Dsonar.login=${{ secrets.sonar_token }}
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
